source: .
destination: ./_site
plugins_dir: ./_plugins
layouts_dir: ./_layouts
data_dir: ./_data

encoding:     "utf-8"

# Serving
detach:  false
port:    8080
host:    news.zuhlke.com
baseurl: "" # does not include hostname
url: "http://news.zuhlke.com"

title: Zuhlke UK News
description: All Zuhlke UK News in one place
google_analytics:
theme: jekyll-theme-cayman

github:
  is_project_page: true
  owner_name: Raul Rodriguez
  owner_url: https://github.com/raulra08/
  repository_name: aws-cloud-formation
  repository_url: https://github.com/raulra08/aws-cloud-formation

include: ['_pages']
